apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-config
  namespace: iot-platform
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "iot_db"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_TOPIC: "iot.telemetry"
  KAFKA_GROUP_ID: "iot-worker-group"
