apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  namespace: iot-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: iot-simulator:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: iot-config
